### ISSUE TITLE
Support declarative DSL style

### ISSUE THREAD

**Issue by gvolpe** [profunktor/fs2-rabbit#201]
Explore the idea of adding a DSL stype API, using the builder pattern as other libraries do. 

Here's an example of how it's done now:

```scala
def p1(R: Fs2Rabbit[IO]) =
  R.createConnectionChannel.use { implicit channel =>
    R.declareExchange(ex, ExchangeType.Topic) *>
    R.declareQueue(DeclarationQueueConfig.default(q1)) *>
    R.bindQueue(q1, ex, rk) *>
    R.createAutoAckConsumer[String](q1)
  }
```

By introducing a DSL we should be able to do it in this way:

```scala
def p1(client: Fs2Rabbit[IO]) =
  client.createConnectionChannel.use { implicit channel =>
    client
      .declareExchange(ex, ExchangeType.Topic)
      .declareQueue(DeclarationQueueConfig.default(q1)) 
      .bindQueue(q1, ex, rk) *>
    client.createAutoAckConsumer[String](q1)
  }
```

Both ways should be equivalent but probably the DSL style is more friendly.

Essentially any method returning `F[Unit]` could be added to the DSL.

**Comment by Daenyth** [comment]
I'd honestly rather see one way to do things. It'll be a smaller API to maintain, and it will be easier for consumers (who might be new to cats-effect etc) to figure out what code means and when to use what construct

**Comment by gvolpe** [comment]
Thanks for the feedback (and the remainder to look into this). It was more of an idea but I abandoned it as soon as the next day so it was never going to happen :smile:
