### ISSUE TITLE
Have to hack around to support client side SSL certificate authentication (SASL EXTERNAL)

### ISSUE THREAD

**Issue by changlinli** [profunktor/fs2-rabbit#212]
Although RabbitMQ comes with a plugin for doing SSL-based authentication which is supported by the RabbitMQ Java client library, `fs2-rabbit` doesn't expose that. There is a workaround for it, which looks something like the following:

```scala
package dev.profunktor.fs2rabbit

import cats.effect.ConcurrentEffect
import cats.syntax.functor._
import com.rabbitmq.client.DefaultSaslConfig
import dev.profunktor.fs2rabbit.config.Fs2RabbitConfig
import dev.profunktor.fs2rabbit.interpreter.{AmqpClientEffect, ConnectionEffect, Fs2Rabbit, LiveInternalQueue}
import dev.profunktor.fs2rabbit.program.{AckingProgram, ConsumingProgram}
import javax.net.ssl.SSLContext

object Blah {

  def customCreateFs2Rabbit[F[_] : ConcurrentEffect](config: Fs2RabbitConfig, sslContext: Option[SSLContext]): F[Fs2Rabbit[F]] = {
    ConnectionEffect.mkConnectionFactory[F](config, sslContext).map {
      case (factory, addresses) =>
        val saslConfig = DefaultSaslConfig.EXTERNAL
        factory.setSaslConfig(saslConfig)
        val amqpClient = new AmqpClientEffect[F]
        val conn       = new ConnectionEffect[F](factory, addresses)
        val internalQ  = new LiveInternalQueue[F](config.internalQueueSize.getOrElse(500))
        val acker      = new AckingProgram[F](config, amqpClient)
        val consumer   = new ConsumingProgram[F](amqpClient, internalQ)
        new Fs2Rabbit[F](conn, amqpClient, acker, consumer)
    }
  }
}
```

which you then use to create an `Fs2Rabbit[F]` instead of the usual way, but because `mkConnectionFactory` is `private[fs2rabbit]`, this file has to be put in a `dev.profunktor.fs2rabbit` namespace, which is kind of annoying. Not a show-stopper, but is a bit of a rough edge for the library.

**Comment by changlinli** [comment]
If you agree that this is a problem, I can think of two main lines of fixing it; either expose a way of directly translating a `ConnectionFactory` into an `Fs2Rabbit` (and highlight that this is not the usual way you do things) as a sort of backdoor for any other features in the Java library that aren't supported by the FS2 wrapper or bake in SASL config support into the FS2 wrapper.

**Comment by gvolpe** [comment]
This should be supported by the library. We could probably add an `Option[SASLConfig]` in the same way we have an `Option[SSLContext]`. Or maybe something else...
