### ISSUE TITLE
Separate thread pool for blocking publish operations

### ISSUE THREAD

**Issue by alexander-branevskiy** [profunktor/fs2-rabbit#230]
Seems that the current implementation of message publishing has some deficiencies. It uses native Rabbit MQ client as a transport and its ```basicPublish``` operation can block a thread what can lead to several problems like API freezing (in case if it uses the same thread pool), overall performance degradation, etc... So i suggest either moving all operations related to ```basicPublish``` to a separate thread pool (fixed?) or try to use NIO rabbit MQ client API (not sure whether it will help) in order to resolve the problem.

**Comment by gvolpe** [comment]
In the meantime, I think you can get away by wrapping the publishing call in a blocking execution context. Either using `ContextShift` or `Blocker` if using a newer version of `cats-effect`. Something like:

```scala
def publishSimpleMessage[F[_]: Sync](blocker: Blocker[F], publisher: String => F[Unit]): F[Unit] =
  blocker.blockOn(publisher("Hello world!"))
```

Or in older versions:

```scala
def publishSimpleMessage[F[_]: ContextShift: Sync](publisher: String => F[Unit]): F[Unit] =
  ContextShift[F].evalOn(publisher("Hello world!"))
```
