### ISSUE TITLE
Acker function does not support `basicReject`

### ISSUE THREAD

**Issue by DougC** [profunktor/fs2-rabbit#300]
The Acker only allows for `Ack` and `NAck`, but not `Reject`

https://github.com/profunktor/fs2-rabbit/blob/f5012a889ff5468e2d69c7cbe2a1cbbdf2793ca1/core/src/main/scala/dev/profunktor/fs2rabbit/program/AckingProgram.scala#L40

**Comment by DougC** [comment]
See https://www.rabbitmq.com/api-guide.html#recovery-and-acknowledgements for discussion of `basicReject`. Reject is useful for supporting deadletter exchanges

**Comment by gvolpe** [comment]
This should be fairly easy to add :wink:

**Comment by DougC** [comment]
PR here https://github.com/profunktor/fs2-rabbit/pull/301 :-)
