### ISSUE TITLE
Microsite is not available

### ISSUE THREAD

**Issue by kubum** [profunktor/fs2-rabbit#396]
I remember not that long time ago I used to send links to https://fs2-rabbit.profunktor.dev/ and it was working, but since the last week it is not loading. I wonder did something break the publishing to Github Pages or something else? Do you need a hand to fix it?

**Comment by gvolpe** [comment]
Weird... It works for me. Try cleaning up your cache?

**Comment by kubum** [comment]
Uh oh this is awkward! You are right. After I removed a file `/etc/resolver/dev` that was created by early versions of Docker for Mac ([found a commit of its removal](https://github.com/docker/kitematic/pull/27/files#diff-459fc1a35a20fde5c95a67ae9bd00e7aL4-L5)) the host started to resolve. Who knew .dev domain became [available in 2019](https://en.wikipedia.org/wiki/.dev) and they all never loaded for me on this machine due to the early resolver docker left 😆

```$ cat /etc/resolver/dev
nameserver 172.17.42.1
```

I am sorry!
