### ISSUE TITLE
Allow configuring the ConnectionResource ThreadFactory

### ISSUE THREAD

**Issue by Daenyth** [profunktor/fs2-rabbit#403]
By default, the java library `ConnectionFactory` used in `Connection.scala` uses a `DefaultThreadFactory`, which produces unhelpful names like `pool-N-thread-M`.

The `ConnectionFactory` exposes a `setThreadFactory` method; it would be helpful to expose that as an `Option[F[ThreadFactory]]` parameter on `RabbitClient.apply`.

We should be able to preserve backwards compatibility by doing this as an overloaded `apply` method, rather than using a default parameter.

**Comment by jbwheatley** [comment]
fixed in 4.0.0 (requires cats-effect 3)
