### ISSUE TITLE
Update to cats-effect 3.x ecosystem

### ISSUE THREAD

**Issue by Daenyth** [profunktor/fs2-rabbit#420]
Need to get on it so the ecosystem can keep moving :)

Ref https://github.com/typelevel/cats-effect/issues/1330

**Comment by jbwheatley** [comment]
I've started a WIP branch for cats-effect 3: `ce3`. Tests all passing, but the monix and zio examples don't compile.

**Comment by Daenyth** [comment]
@jbwheatley Can you open a draft PR for visibility?

**Comment by jbwheatley** [comment]
#434

**Comment by jbwheatley** [comment]
completed in 4.0.0
