### ISSUE TITLE
Allow "multiple" ack flag to be reset per call

### ISSUE THREAD

**Issue by Daenyth** [profunktor/fs2-rabbit#461]
Right now, the "ack multiple messages" property gets set on creation, but I believe the api allows it to be set per call. That would be better, because it allows an application to use mixed modes where convenient. I think it's reasonable to keep the creation-time setting as a default, and have overrides that allow it to be set later.

**Comment by jbwheatley** [comment]
fixed in 4.0.0 (requires cats-effect 3)
