### ISSUE TITLE
Durations in Fs2RabbitConfig

### ISSUE THREAD

**Issue by DStranger** [profunktor/fs2-rabbit#474]
Hi guys!

Fs2RabbitConfig currently uses ints for durations, which is confusing:
`connectionTimeout` is defined in milliseconds,
`requestedHeartbeat` is defined in seconds.

Moreover, official examples use a very low value for `connectionTimeout` (3), which causes issues when being used in real environments, and adds to the confusion.

This can be solved in multiple ways, but I think the best solution would be to be able to specify durations as such (10 s, etc).
This would introduce some backward compatibility problems, so I'm curious what you think.

**Comment by jbwheatley** [comment]
fixed in 4.0.0 (requires cats-effect 3)
