### ISSUE TITLE
Expired gpg key

### ISSUE THREAD

**Issue by jbwheatley** [profunktor/fs2-rabbit#738]
@gvolpe @Daenyth do either of you have access to update this? Cannot release this library currently: https://github.com/profunktor/fs2-rabbit/actions/runs/3189902245/jobs/5204276942

**Comment by faustin0** [comment]
Hi, any news on this? is the library release process still blocked because of the expired key?

**Comment by matejcerny** [comment]
@gvolpe Can you please unplug this issue so guys can do releases again? Pretty please! 🙏

**Comment by gvolpe** [comment]
Hey everyone, sorry this was blocking you. @matejcerny reached out to me via email, that's how I found out, as I don't get any notifications for any ping on this repo (deliberate choice when I left it).

I've made both @jbwheatley and @matejcerny administrators, so you should be able to create a new GPG key and update the environment variables accordingly here: https://github.com/profunktor/fs2-rabbit/settings/secrets/actions

**Comment by matejcerny** [comment]
Key updated, I will close this issue after I successfully create a new release.

**Comment by matejcerny** [comment]
More painful than I expected, but hey, here we go! 😸 https://github.com/profunktor/fs2-rabbit/releases/tag/v5.1.0
