### ISSUE TITLE
Can't create a publisher to publish directly to a queue?

### ISSUE THREAD

**Issue by DougC** [profunktor/fs2-rabbit#766]
I may be missing something obvious, but I want to create a publisher that will publish messages directly to a queue and I can't see a method on `RabbitClient` that will allow me to do that. All the `createPublisher` methods expect an exchange name and routing key.

Essentially I'm after doing what's described in this example https://rabbitmq.com/tutorials/tutorial-one-java.html

**Comment by faustin0** [comment]
Hi @DougC , maybe you want to publish using the default exchange mechanism ?
https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-default
So, passing an empty exchange name and a routing key that matching the queue name you expect.
Something like this:
`client.createPublisher[String](
                      ExchangeName(""),
                      RoutingKey("my-queue-name")
                    )`
