### ISSUE TITLE
Stop supporting Scala 2.12 

### ISSUE THREAD

**Issue by geirolz** [profunktor/fs2-rabbit#977]
Opening this ticket to talk about scala 2.12 support. 
I wonder when and if we want to stop supporting it - this creates some limitations due the compatibility and more maintenance work 

Should we consider to stop supporting this version ?

**Comment by matejcerny** [comment]
From the current list of adopters: @orium @ybasket @sentenza

**Comment by geirolz** [comment]
Planned for version 5.4.0

**Comment by matejcerny** [comment]
> Planned for version [5.4.0](https://github.com/profunktor/fs2-rabbit/milestone/3)

Please add some exclamation marks in the release description 😄
