### ISSUE TITLE
Releases are failing

### ISSUE THREAD

**Issue by geirolz** [profunktor/fs2-rabbit#986]
All releases since a while are failing with this message:

> java.net.ProtocolException: Server redirected too many  times (20)

Any idea ? 

Did we update the auth method to Sonatype from username-password to user token ? 
https://central.sonatype.org/publish/generate-token/

**Comment by geirolz** [comment]
@matejcerny can you please have a look too ?

**Comment by matejcerny** [comment]
Sadly we will need a help from @gvolpe as I don't have access to sonatype.

**Comment by geirolz** [comment]
All releases are stuck until we fix this, since it's the second time I'd say that at least you @matejcerny should have sonatype access. 
@gvolpe Can you please help us ?

**Comment by matejcerny** [comment]
I have contacted Gabriel via email. In the meantime, I made you an admin @geirolz as you are the most active anyway.

**Comment by gvolpe** [comment]
Fixed: https://github.com/profunktor/fs2-rabbit/actions/runs/11385486599/job/31822567302

re: access to sonatype: this is my private account, not something I can share. Also, he UI/UX is quite bad on sonatype, not sure if they would allow share publishing access to the same target `dev.profunktor` from different accounts, but I think it's worth asking the question to the sonatype folks if you would like to try.

**Comment by matejcerny** [comment]
We have already dealt with this error. Last time, there were some "dirty" files in Git that were generated by a plugin. This time it's because of a scalafmt.

**Comment by matejcerny** [comment]
I have fixed and re-released it: https://oss.sonatype.org/service/local/repositories/releases/content/dev/profunktor/fs2-rabbit_3/5.3.0/fs2-rabbit_3-5.3.0.jar
